TASK-3: OOP principles (fixed review notes)
daverbk/aqa-studies-iTechArt-lab pull request #10
Opened 2022-02-18 08:03 UTC by daverbk

2022-02-18 08:59 UTC, mashadolya requested changes

2022-02-18 08:59 UTC, mashadolya commented on Drivers/BogusDriversFiller.cs
> +        }
Что за 5? и можно сделать 

`return DateTime.Now.Year - driver.DateGotDrivingLicense.Year < 5? false: true`

2022-02-18 08:59 UTC, mashadolya commented on Drivers/BogusDriversFiller.cs
> +        public static bool CheckIfEnoughDrivingExp(Driver driver)
не сокращай названия

2022-02-18 08:59 UTC, mashadolya commented on Drivers/BogusDriversFiller.cs
> +        public static List<Driver> FillDriver(int count)
мб `GenerateDrivers(count)`?

2022-02-18 08:59 UTC, mashadolya commented on Drivers/BogusDriversFiller.cs
> +    public static class BogusDriversFiller
DriverFactory 
DriverGeneartor

2022-02-18 08:59 UTC, mashadolya commented on Drivers/BogusEnginesFiller.cs
> +        private const int UpperBoundaryMaxSpeed = 220;
можно создать статик класс констант

class HoursePower{
const min = .....

}

class EngineeCapacity {}

2022-02-18 08:59 UTC, mashadolya commented on Drivers/Driver.cs
>                  while (value < DateOfBirth || value.Year - DateOfBirth.Year < 16)
опять меджик намберс

2022-02-18 08:59 UTC, mashadolya commented on Drivers/Driver.cs
> +                    value = BogusDriversFiller.FillDriver(1)[0].DateGotDrivingLicense;
Тоже

2022-02-18 08:59 UTC, mashadolya commented on Drivers/Menu.cs
> -            return _selectedIndex;
а можно это все через свитч кейс как нибудь?

2022-02-18 08:59 UTC, mashadolya commented on Drivers/Program.cs
> +            // DEVNOTE: Generating some amount of vehicles of different type to provide the logic
Можно создать доп класс который будет заполнять энджин и тд и возвращать уже готовую машину тут

2022-02-18 08:59 UTC, mashadolya commented on Drivers/UserInterface.cs
> +
Енамы всегда храним отдельно в директории Enum, которая будет находится в директории склассами, используещими данный енам

2022-02-18 08:59 UTC, mashadolya commented on Drivers/UserInterface.cs
> +        private const string SportCarClassName = "Drivers.SportCar";
Вроде есть что то типа ГетКлассНейм

2022-02-18 09:02 UTC, mashadolya commented
В пр тайте не надо указывать фикс ревью, просто заливаешь ченжи и все , по комитам и так будет видно

2022-02-19 09:06 UTC, daverbk commented on Drivers/UserInterface.cs
> +        private const string SportCarClassName = "Drivers.SportCar";
Попробовал вписать через typeof(Minivan).GetType().ToString(), как я понял, константу нельзя инициализировать с помощью методов, ибо константы не могут быть определены во время рантайма :(
Надеюсь, я правильно понял твой коммент 🙏🙏🙏

2023-06-13 05:49 UTC, closed without merging